version: '3'

services:
  eflush-db:
    container_name: eflush-db
    image: postgres:14.5
    ports:
     - "5656:5432"
    environment:
     POSTGRES_DB: eflush_db
     POSTGRES_USER: eflush
     POSTGRES_PASSWORD: password
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d/
